<?php
/**
 * Product list template
 *
 * @var $block \SM\SumUp\Block\Post\RelatedProduct
 */

use Magento\Framework\App\Action\Action;

$_productCollection = $block->getLoadedProductCollection();
$_helper = $block->getHelper();
$pos = $block->getPositioned();
$imageDisplayArea = 'category_page_list';
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
$viewMode = 'list';
$showDescription = true;

?>
<?php if (!$_productCollection->count()) : ?>
    <div class="message info empty">
        <div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else : ?>
    <div class="hbr-main pad-main">
        <div class="block-title-main">
            <div class="title-border"></div>
        </div>
        <div class="hbr-main">
            <div style="margin: 0 -10px;">
                <div class="hbr-content hbr-slider">
                    <?php foreach ($_productCollection as $_product) : ?>
                        <div class="hbr-inner">
                            <div class=" hbr-inner item product product-item mp-blog-slider-item">
                                <div class="product-item-info" data-container="product-<?= /* @noEscape */
                                $viewMode ?>">
                                    <?php
                                    $productImage = $block->getImage($_product, $imageDisplayArea);
                                    if ($pos != null) {
                                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                            . 'top:' . $productImage->getHeight() . 'px;"';
                                    }
                                    ?>
                                    <?php // Product Image?>
                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                       class="product photo product-item-photo"
                                       tabindex="-1">
                                        <?= $productImage->toHtml() ?>
                                    </a>
                                    <div class="product details product-item-details">
                                        <?php
                                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                        ?>
                                        <strong class="product name product-item-name">
                                            <a class="product-item-link"
                                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                                <?= /* @noEscape */
                                                $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                            </a>
                                        </strong>
                                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                        <?= /* @noEscape */
                                        $block->getProductPrice($_product) ?>
                                        <?= $block->getProductDetailsHtml($_product) ?>
                                        <!---->
                                        <div class="product-item-inner">
                                            <div
                                                class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                <div
                                                    class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                    <?php if ($_product->isSaleable()) : ?>
                                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>

                                                        <form data-role="tocart-form"
                                                              data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                                                              method="post">
                                                            <input type="hidden"
                                                                   name="product"
                                                                   value="<?= /* @noEscape */
                                                                   $postParams['data']['product'] ?>">
                                                            <input type="hidden" name="<?= /* @noEscape */
                                                            Action::PARAM_NAME_URL_ENCODED ?>"
                                                                   value="<?= /* @noEscape */
                                                                   $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                            <?= $block->getBlockHtml('formkey') ?>
                                                            <button type="submit"
                                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                                    class="action tocart primary">
                                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                                            </button>
                                                        </form>
                                                    <?php else : ?>
                                                        <?php if ($_product->isAvailable()) : ?>
                                                            <div class="stock available">
                                                                <span><?= $block->escapeHtml(__('In stock')) ?></span>
                                                            </div>
                                                        <?php else : ?>
                                                            <div class="stock unavailable">
                                                                <span><?= $block->escapeHtml(__('Out of stock')) ?></span>
                                                            </div>
                                                        <?php endif; ?>
                                                    <?php endif; ?>
                                                </div>
                                                <div data-role="add-to-links"
                                                     class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>>
                                                    <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                            <?php if ($showDescription) : ?>
                                                <div class="product description product-item-description">
                                                    <?= /* @noEscape */
                                                    $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                                                       title="<?= /* @noEscape */
                                                       $_productNameStripped ?>"
                                                       class="action more"><?= $block->escapeHtml(__('Learn More')) ?></a>
                                                </div>
                                            <?php endif; ?>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>

                </div>

            </div>
            <script type="text/javascript" xml="space">// <![CDATA[
                require(['jquery', 'cpowlcarousel'], function ($) {
                    jQuery(document).ready(function () {
                        jQuery(".hbr-slider").owlCarousel({
                            items: 3,
                            itemsDesktop: [1080, 4],
                            itemsDesktopSmall: [860, 3],
                            itemsTablet: [768, 3],
                            itemsTabletSmall: [639, 3],
                            itemsMobile: [479, 2],
                            pagination: false,
                            navigationText: ['<div class="lft-btn"><i class="fa fa-angle-left"></i></div>', '<div class="rgt-btn"><i class="fa fa-angle-right"></div>'],
                            navigation: true,
                        });
                    });
                });
                // ]]></script>
        </div>
    </div>
<?php endif; ?>
