<?php


/** @var \SM\SumUp\Block\Frontend $block */
?>


<div class="post-list-content" id="mpblog-list-container">
    <?php $postCollection = $block->getPostCollection(); ?>

    <?php if ($postCollection && $postCollection->getSize()) : ?>
        <div class="post-list-body">
            <?php $i = 1 ?>
            <?php /** @var \SM\SumUp\Model\Post $post */
            foreach ($postCollection as $post) : ?>

                <div class="post-list-item col-mp post-item-list mp-12">

                    <div class="post-item-wraper">
                            <div class="post-image">
                                <a href="<?= $post->getUrl() ?>">
                                    <img class="img-responsive"
                                         src="<?= $block->resizeImage($post->getImage(), '400x'); ?>"
                                         alt="<?= $block->escapeHtml($post->getName()); ?>"/>
                                </a>
                            </div>
                        <div class="post-info-wraper">
                            <h2 class="mp-post-title">
                                <a class="post-link-title" title="<?= $block->escapeHtml($post->getName()); ?>"
                                   href="<?= $post->getUrl() ?>">
                                    <?= $post->getName(); ?>
                                </a>
                            </h2>

                            <div class="post-short-description">
                                <p><?= $block->maxShortDescription($post->getShortDescription()); ?></p>
                            </div>
                            <div class="mp-clearfix"></div>
                            <div class="mp-post-meta-info mp-alignright">
                                <div class="actions">
                                    <a class="mp-read-more" href="<?= $post->getUrl(); ?>"
                                       title="<?= __('Read More'); ?>">
                                        <?= __('Read More'); ?>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php if ($i++ % 2 == 0) : ?>
                    <div class="mp-clear"></div>
                <?php endif; ?>
            <?php endforeach; ?>
            <div class="mp-clear"></div>
        </div>
        <?= $block->getPagerHtml() ?>
    <?php else : ?>
        <?= __('There are no posts at this moment'); ?>
    <?php endif; ?>
    <?= $this->getChildHtml('additional'); ?>
</div>
<script>
    require(['jquery'], function ($) {
        $('.limiter').css('float', 'right');
    });
</script>

