<?php


use SM\SumUp\Model\Config\Source\Comments\Type;

/** @var \SM\SumUp\Block\Post\View $block */

/** @var \SM\SumUp\Helper\Data $helper */
$helper = $block->getBlogHelper();

$_post = $block->getPost();

$author = $helper->getAuthorByPost($_post);
$authorName = $author !== null ? $author->getName() : '';

$modifier = $helper->getAuthorByPost($_post, true);
$modifierName = $modifier !== null ? $modifier->getName() : '';
$isLogged = ($block->isLoggedIn()) ? 'Yes' : 'No';
$color = $helper->getBlogConfig('general/font_color');
?>
<div class="mp-blog-view">

    <div class="mpcss post-view" id="mpblog-list-container">
        <div class="post-list-content col-md-12 col-sm-8">
            <div class="post-view-image col-xs-12">
                <?php if ($_post->getImage()) : ?>
                    <img class="img-responsive"  src="<?= /* @noEscape */ $block->getImageUrl($_post->getImage()) ?>"  width="500" height="600"
                         alt="<?= $block->escapeHtml($_post->getName()) ?>"/>
                <?php endif; ?>
            </div>
            <div class="post-post_content col-xs-12">

                <?= /* @noEscape */ $block->getPageFilter($_post->getDescription()?:'') ?>
            </div>
            <div class="mp-clear"></div>
            <div class="col-xs-12">
                <hr/>
                <div class="mp-post-info">
                    <span><i class="fa fa-calendar-times-o">&nbsp;</i>
                        <?= /* @noEscape */ $block->getDateFormat($_post->getPublish_date()) ?>
                    </span>

                    <?php if ($categoryHtml = $block->getPostCategoryHtml($_post)) : ?>
                        |
                        <span><i class="fa fa-folder-open-o">&nbsp;</i>
                            <?= /* @noEscape */ __('Categories: %1', $categoryHtml); ?>
                        </span>
                    <?php endif; ?>
                    <?php if ($tagList = $block->getTagList($_post)) : ?>
                        | <span><i class="fa fa-tags"></i><?= /* @noEscape */ __('Tags: %1', $tagList); ?></span>
                    <?php endif; ?>
                    <?php if ($authorName && $helper->showAuthorInfo()) : ?>
                        |
                        <span><i class="fa fa-user">&nbsp;</i><?= /* @noEscape */ __('By: %1', '<a class="mp-info" href="' . $author->getUrl() . '">' . $authorName . '</a>') ?></span>
                        <?php if ($authorName != $modifierName && $modifierName) : ?>
                            |
                            <span><i class="fa fa-edit">&nbsp;</i><?= /* @noEscape */ __('Modify By: %1 at %2', '<a class="mp-info" href="' . $modifier->getUrl() . '">' . $modifierName . '</a>', $block->getDateFormat($_post->getUpdatedAt())) ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <hr/>
            </div>
        </div>
    </div>

    <?php if ($authorName && $helper->showAuthorInfo()) :
        $block->resizeImage($author->getImage(), '135x', \SM\SumUp\Helper\Image::TEMPLATE_MEDIA_TYPE_AUTH);
        ?>
        <div class="block-blog-related about-admin">
            <h2><?= /* @noEscape */ __('About the Author'); ?></h2>
            <div class="related-content-container">
                <div class="author-content-image">
                    <img class="img-responsive"
                         src="<?= /* @noEscape */ $author->getImage()
                             ? $block->resizeImage(
                                 $author->getImage(),
                                 '135x',
                                 \SM\SumUp\Helper\Image::TEMPLATE_MEDIA_TYPE_AUTH
                             ) : $block->getDefaultAuthorImage() ?>">
                </div>
                <div class="author-content-information">
                    <div class="author-name"><?= /* @noEscape */ $authorName ?></div>
                    <p class="author-description">
                        <?= /* @noEscape */ $author->getShortDescription()
                            ? $block->getPageFilter($author->getShortDescription()):'' ?>
                    </p>
                </div>
                <div class="mp-clear"></div>
            </div>
        </div>
    <?php endif; ?>

    <?php $relatedPosts = $_post->getRelatedPostsCollection(); ?>
    <?php if ($relatedPosts && count($relatedPosts)) : ?>
        <div class="block-blog-related topic-list mpcss" style="width: 90%;">
            <h2><?= /* @noEscape */ __('Related Posts'); ?></h2>
            <?php if ($block->getRelatedMode()) :?>
                <div class="owl-carousel owl-theme">
                    <?php foreach ($relatedPosts as $post) : ?>
                        <div class="item post-list-item ">
                            <div class="post-item-wraper">
                                <div class="post-image">
                                    <?php if ($post->getImage()) : ?>
                                        <a href="<?= /* @noEscape */ $post->getUrl() ?>">
                                            <img class="img-responsive"
                                                 src="<?= /* @noEscape */ $block->resizeImage(
                                                     $post->getImage(),
                                                     '400x'
                                                 ) ?>"
                                                 alt="<?= /* @noEscape */ $block->escapeHtml($post->getName()) ?>"/>
                                        </a>
                                    <?php endif; ?>
                                </div>
                                <div class="post-info-wraper">
                                    <h2 class="mp-post-title">
                                        <a class="post-link-title"
                                           title="<?= $block->escapeHtml($post->getName()) ?>"
                                           href="<?= /* @noEscape */ $post->getUrl() ?>">
                                            <?= /* @noEscape */ $post->getName(); ?>
                                        </a>
                                    </h2>
                                    <div class="mp-post-info">
                                        <?= /* @noEscape */ $block->getPostInfo($post); ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
                <style>
                    .item.post-list-item.col-mp{
                        width: 100%;
                    }
                </style>
                <script>
                    require([
                        'jquery',
                        'owlCarousel'
                    ], function ($) {
                        'use strict';
                        $(document).ready(function(){
                            $(".owl-carousel").owlCarousel({
                                items:2,
                                loop:false,
                                margin:10,
                                responsive:{
                                    600:{
                                        items:3
                                    }
                                }
                            });
                        });
                    });
                </script>
            <?php else :?>
                <div class="related-content-container" style="display: flex; flex-wrap: wrap;">
                    <?php foreach ($relatedPosts as $post) : ?>
                        <div class="post-list-item col-mp mp-6 mp-lg-4 mp-md-6 mp-xs-12">
                            <div class="post-item-wraper">
                                <div class="post-image">
                                    <?php if ($post->getImage()) : ?>
                                        <a href="<?= /* @noEscape */ $post->getUrl() ?>">
                                            <img class="img-responsive"
                                                 src="<?= /* @noEscape */ $block->resizeImage($post->getImage(), '400x'); ?>"
                                                 alt="<?= /* @noEscape */ $block->escapeHtml($post->getName()) ?>"/>
                                        </a>
                                    <?php endif; ?>
                                </div>
                                <div class="post-info-wraper">
                                    <h2 class="mp-post-title">
                                        <a class="post-link-title"
                                           title="<?= $block->escapeHtml($post->getName()); ?>"
                                           href="<?= /* @noEscape */ $post->getUrl() ?>">
                                            <?= /* @noEscape */ $post->getName() ?>
                                        </a>
                                    </h2>
                                    <div class="mp-post-info">
                                        <?= /* @noEscape */ $block->getPostInfo($post) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                    <div class="mp-clear"></div>
                </div>
            <?php endif;?>
        </div>
    <?php endif; ?>

        <?php $relatedBlock = $block->getChildBlock('related_products'); ?>
        <?php if ($relatedBlock->hasProduct()) : ?>
            <div class="block-blog-related products-same-post page-products mpcss" style="width: 90%;">
                <h2><?= /* @noEscape */ ($helper->getBlogConfig('product_post/post_detail/title')) ?: __('Related Products') ?></h2>
                <div class="related-content-container">
                    <?= $relatedBlock->toHtml(); ?>
                </div>
            </div>
        <?php endif; ?>


</div>
