<?php


use SM\SumUp\Model\Config\Source\Comments\Type;

/** @var \SM\SumUp\Block\Post\View $block */

/** @var \SM\SumUp\Helper\Data $helper */
$helper = $block->getBlogHelper();

$_post = $block->getPost();

$author = $helper->getAuthorByPost($_post);
$authorName = $author !== null ? $author->getName() : '';

$modifier = $helper->getAuthorByPost($_post, true);
$modifierName = $modifier !== null ? $modifier->getName() : '';
?>

<div class="mp-blog-view">

    <div class="mpcss post-view" id="mpblog-list-container">
        <div class="post-list-content col-md-12 col-sm-8">
            <div class="post-view-image col-xs-12">
                <?php if ($_post->getImage()) : ?>
                    <img class="img-responsive"  src="<?= /* @noEscape */ $block->getImageUrl($_post->getImage()) ?>"  width="500" height="600"
                         alt="<?= $block->escapeHtml($_post->getName()) ?>"/>
                <?php endif; ?>
            </div>
            <div class="post-post_content col-xs-12">
                <?= /* @noEscape */ $block->getPageFilter($_post->getDescription()?:'') ?>
            </div>
            <div class="mp-clear"></div>
            <div class="col-xs-12">
                <hr/>
                <div class="mp-post-info">
                    <span><i class="fa fa-calendar-times-o">&nbsp;</i>
                        <?= /* @noEscape */ $block->getDateFormat($_post->getPublish_date()) ?>
                    </span>

                    <?php if ($categoryHtml = $block->getPostCategoryHtml($_post)) : ?>
                        |
                        <span><i class="fa fa-folder-open-o">&nbsp;</i>
                            <?= /* @noEscape */ __('Categories: %1', $categoryHtml); ?>
                        </span>
                    <?php endif; ?>
                    <?php if ($tagList = $block->getTagList($_post)) : ?>
                        | <span><i class="fa fa-tags"></i><?= /* @noEscape */ __('Tags: %1', $tagList); ?></span>
                    <?php endif; ?>
                    <?php if ($authorName ) : ?>
                        |
                        <span><i class="fa fa-user">&nbsp;</i><?= /* @noEscape */ __('By: %1',$authorName ) ?></span>
                        <?php if ($authorName != $modifierName && $modifierName) : ?>
                            |
                            <span><i class="fa fa-edit">&nbsp;</i><?= /* @noEscape */ __('Modify By: %1 at %2', '<a class="mp-info" href="' . $modifier->getUrl() . '">' . $modifierName . '</a>', $block->getDateFormat($_post->getUpdatedAt())) ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
                <hr/>
            </div>
        </div>
    </div>

    <?php if ($authorName ) :
       if($author->getImage() !== null) {
           $block->resizeImage($author->getImage(), '135x', \SM\SumUp\Helper\Image::TEMPLATE_MEDIA_TYPE_AUTH);
       }
        ?>
        <div class="block-blog-related about-admin">
            <h2><?= /* @noEscape */ __('About the Author'); ?></h2>
            <div class="related-content-container">
                <div class="author-content-image">
                    <img class="img-responsive"
                         src="<?= /* @noEscape */ $author->getImage()
                             ? $block->resizeImage(
                                 $author->getImage(),
                                 '135x',
                                 \SM\SumUp\Helper\Image::TEMPLATE_MEDIA_TYPE_AUTH
                             ) : $block->getDefaultAuthorImage() ?>">
                </div>
                <div class="author-content-information">
                    <div class="author-name"><?= /* @noEscape */ $authorName ?></div>
                    <p class="author-description">
                        <?= /* @noEscape */ $author->getShortDescription()
                            ? $block->getPageFilter($author->getShortDescription()):'' ?>
                    </p>
                </div>
                <div class="mp-clear"></div>
            </div>
        </div>
    <?php endif; ?>


</div>
